### ISSUE TITLE
Dynamic Zero Config Prometheus setup

### ISSUE THREAD

**Issue by chrisbecke** [neuroforgede/swarmsible#4]
## Description

As a consumer of a Swarm, I want to deploy a stack that contains its own Prometheus instance. This prometheus instance already knows how to scrape all the services in this stack. However, all the metrics need to be scraped by the swarms main Prometheus instance to arrive in the central Grafana dashboard.

## Proposal

The main prometheus instance can contain a federation job. Something like this :-

```yaml
  - job_name: federate-prometheus
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~".*"}'
    dns_sd_configs:
    - names: [ tasks.scrape.target ]
      type: 'A'
      port: 9090
```

Two additional requirements are present: a common prometheus network, and a convention based naming approach: each child prometheus instance needs to add itself to the common prometheus network, and declare an alias there that allows its discovery by the main Prometheus instance.

Stack local prometheus instances could use this minimal declaration to become eligable for scraping.

```yaml
networks:
  prometheus:
    external: true
    
services:
   prometheus:
     networks:
       default:
       prometheus: 
         aliases: ["scrape.target"]
```

*Result*
By probing `scrape.target` via `dns_sd_configs` the main instance gets a dynamic list of IPs of all active stack local prometheus instances, and grabs all their metrics via the `/federate` endpoint.
